

//--Error Log: 2017-12-23 03:04:59.035192 -> Exception: division by zero --  -- function: GetTaskList , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\GetMechanism\GetTask.py

//--Error Log: 2017-12-23 03:04:59.061696 -> Exception: 'NoneType' object is not iterable --  -- function: TaskForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-25 19:23:14.629831 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:23:17.174734 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:23:18.747420 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:26:01.096004 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:26:11.402724 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:26:29.113027 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:33:29.072063 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:34:49.594984 -> Exception: division by zero --  -- function: CompForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\CompanyFunc.py

//--Error Log: 2017-12-25 19:40:07.154328 -> Exception: name 'render_template' is not defined

//--Error Log: 2017-12-25 19:40:28.294904 -> Exception: Could not build url for endpoint 'projb.ProjOverv'. Did you mean 'Index' instead?

//--Error Log: 2017-12-25 19:50:03.090545 -> Exception: Could not build url for endpoint 'projb.ProjTaskForm'. Did you mean 'taskb.ProjTaskForm' instead? --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-25 19:51:29.771595 -> Exception: Could not build url for endpoint 'taskb.TaskForm'. Did you mean 'taskb.ProjTaskForm' instead?

//--Error Log: 2017-12-25 19:51:31.076288 -> Exception: Could not build url for endpoint 'taskb.TaskForm'. Did you mean 'taskb.ProjTaskForm' instead?

//--Error Log: 2017-12-25 19:51:32.080584 -> Exception: Could not build url for endpoint 'taskb.TaskForm'. Did you mean 'taskb.ProjTaskForm' instead?

//--Error Log: 2017-12-25 19:52:30.583671 -> Exception: Could not build url for endpoint 'projb.ProjTaskForm'. Did you mean 'taskb.ProjTaskForm' instead? --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-25 19:54:54.254876 -> Exception: Could not build url for endpoint 'projb.ProjTaskForm'. Did you mean 'taskb.ProjTaskForm' instead? --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-25 20:29:34.380099 -> Exception: name 'inspect' is not defined --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-25 20:30:59.402581 -> Exception: local variable 'i' referenced before assignment --  -- function: ITask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\InsertMechanism\InsertTask.py

//--Error Log: 2017-12-25 22:21:09.916090 -> Exception: no such column: RE1201_CMContr.CMProjID --  -- function: GetProjectContractListByID , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\GetMechanism\GetProjects.py

//--Error Log: 2017-12-25 22:21:09.936093 -> Exception: Encountered unknown tag 'of'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'. --  -- function: ProjTaskForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-25 22:25:22.584250 -> Exception: no such column: RE1201_CMContr.CMProjID --  -- function: GetProjectContractListByID , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\GetMechanism\GetProjects.py

//--Error Log: 2017-12-25 22:25:22.601276 -> Exception: 'NoneType' object is not iterable --  -- function: ProjTaskForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 03:24:09.803803 -> Exception: Could not build url for endpoint 'ProjForm'. Did you mean 'projb.ProjTaskForm' instead? --  -- function: ProjOverv , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 03:44:19.743828 -> Exception: Could not build url for endpoint 'ProjForm'. Did you mean 'projb.ProjForm' instead? --  -- function: ProjOverv , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 04:18:24.750452 -> Exception: Could not build url for endpoint ''. Did you mean 'contrb.ContrForm' instead? --  -- function: ProjForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 05:06:17.044900 -> Exception: Could not build url for endpoint ''. Did you mean 'contrb.ContrForm' instead? --  -- function: ProjForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 05:34:02.062439 -> Exception: no such column: CMContrID --  -- function: IProj , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\InsertMechanism\InsertProject.py

//--Error Log: 2017-12-26 11:46:30.300206 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:00:12.425938 -> Exception: name 'GetProjectByID' is not defined --  -- function: ProjTaskForm , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 12:01:55.842902 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:03:20.486695 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:09:22.570304 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:14:57.392199 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:18:33.980607 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:21:15.507098 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:21:25.191556 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:22:20.956827 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:24:33.045320 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:25:13.144498 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:26:28.715241 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:27:05.239097 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:27:28.045832 -> Exception: name 'TaskName' is not defined --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:27:44.128037 -> Exception: name 'ProjID' is not defined --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:28:06.049174 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:28:29.914935 -> Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 12:29:57.680443 -> Exception: name 'Pos' is not defined --  -- function: AddTask , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\TaskFunc.py

//--Error Log: 2017-12-26 15:31:52.957573 -> Exception: no filter named 'Length' --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 16:13:04.980211 -> Exception: argument of type 'int' is not iterable --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:24:59.717852 -> Exception: Encountered unknown tag 'TaskDepRows'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'. --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:25:35.189849 -> Exception: Encountered unknown tag 'TaskDepRow'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'. --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:25:39.415284 -> Exception: Encountered unknown tag 'TaskDepRow'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'. --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:26:13.940444 -> Exception: expected token 'in', got '|' --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:26:18.331833 -> Exception: expected token 'in', got '|' --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:27:54.388095 -> Exception: unexpected '}' --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py

//--Error Log: 2017-12-26 17:28:39.261163 -> Exception: Encountered unknown tag 'endfor'. --  -- function: ProjTaskDisplay , From file: C:\Users\jonas\AppData\Local\Programs\Python\Python36-32\Scripts\venv\CMApp\Source\modules\ProjectFunc.py